<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{21b87483-29ec-4e1e-868f-12be3b6a0f39}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN

VAR PERSISTENT
	
test : BOOL;

END_VAR

VAR
	
// Users can read pragmas in TcHmi
trafficLight01 	: ST_TrafficLight;

// These are user defined pragams which can bring meaning to different symbol instances
{attribute 'Access' := 'Admin'}
trafficLight02 	: ST_TrafficLight;

{attribute 'Theme' := 'Dark'}
trafficLight03 	: ST_TrafficLight;

NonTrafficLightSymbol : BOOL;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>